// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperHeroesGraphQL.Context;

#nullable disable

namespace SuperHeroesGraphQL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240116214039_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SuperHeroesGraphQL.Entities.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SuperHeroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SuperHeroId");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1852deb8-bc3e-4931-901c-b65d855ba8c2"),
                            Description = "Superman is a fictional superhero. The character was created by writer Jerry Siegel and artist Joe Shuster, and first appeared in the comic book Action Comics #1 (cover-dated June 1938 and published April 18, 1938).",
                            SuperHeroId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Superman"
                        },
                        new
                        {
                            Id = new Guid("fb584691-98ce-4951-9293-15be12ca6cd0"),
                            Description = "Batman is a fictional superhero appearing in American comic books published by DC Comics. The character was created by artist Bob Kane and writer Bill Finger,[2][3] and first appeared in Detective Comics #27 (May 1939).",
                            SuperHeroId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Title = "Batman"
                        });
                });

            modelBuilder.Entity("SuperHeroesGraphQL.Entities.Power", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SuperHeroId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SuperPower")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SuperHeroId");

                    b.ToTable("Power");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1852deb8-bc3e-4931-901c-b65d855ba8c2"),
                            Description = "Superman's powers include incredible strength, the ability to fly, and invulnerability.",
                            SuperHeroId = new Guid("1852deb8-bc3e-4931-901c-b65d855ba8c2"),
                            SuperPower = "Superhuman strength, speed, stamina and durability"
                        },
                        new
                        {
                            Id = new Guid("fb584691-98ce-4951-9293-15be12ca6cd0"),
                            Description = "Batman's primary character traits can be summarized as \"wealthy, physical prowess, deductive abilities and obsession\".",
                            SuperHeroId = new Guid("fb584691-98ce-4951-9293-15be12ca6cd0"),
                            SuperPower = "Genius-level intellect"
                        });
                });

            modelBuilder.Entity("SuperHeroesGraphQL.Entities.SuperHero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SuperHero");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1852deb8-bc3e-4931-901c-b65d855ba8c2"),
                            Description = "Superman is a fictional superhero. The character was created by writer Jerry Siegel and artist Joe Shuster, and first appeared in the comic book Action Comics #1 (cover-dated June 1938 and published April 18, 1938).",
                            Name = "Superman"
                        },
                        new
                        {
                            Id = new Guid("fb584691-98ce-4951-9293-15be12ca6cd0"),
                            Description = "Batman is a fictional superhero appearing in American comic books published by DC Comics. The character was created by artist Bob Kane and writer Bill Finger,[2][3] and first appeared in Detective Comics #27 (May 1939).",
                            Name = "Batman"
                        });
                });

            modelBuilder.Entity("SuperHeroesGraphQL.Entities.Movie", b =>
                {
                    b.HasOne("SuperHeroesGraphQL.Entities.SuperHero", "SuperHero")
                        .WithMany("Movies")
                        .HasForeignKey("SuperHeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SuperHero");
                });

            modelBuilder.Entity("SuperHeroesGraphQL.Entities.Power", b =>
                {
                    b.HasOne("SuperHeroesGraphQL.Entities.SuperHero", "SuperHero")
                        .WithMany("Powers")
                        .HasForeignKey("SuperHeroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SuperHero");
                });

            modelBuilder.Entity("SuperHeroesGraphQL.Entities.SuperHero", b =>
                {
                    b.Navigation("Movies");

                    b.Navigation("Powers");
                });
#pragma warning restore 612, 618
        }
    }
}
